#vcs Make file
RTL_DIR = ./rtl
TB_DIR = ./tb
BUILD_DIR = ./build
INC_DIR = +incdir+$(RTL_DIR)
SIMV_DIR = ./build/simv
SIMV_OPTS := -cm line+cond+fsm+tgl+branch+assert -cm_dir coverage.vdb -cm_name sim1
SIMV_OPTS += +UVM_VERBOSITY=UVM_HIGH
VCS_OPT    = -full64 -sverilog -debug_access+all -kdb -lca \
             -timescale=1ns/1ps \
             -ntb_opts uvm-1.2 \
             -o $(SIMV_DIR)


run:
	mkdir -p $(BUILD_DIR)
	vcs -full64 -sverilog -debug_access+all -kdb -lca \
		-timescale=1ns/1ps \
		-ntb_opts uvm-1.2 \
		-o $(SIMV_DIR) $(RTL_DIR)/ram.sv $(TB_DIR)/tb_ram_uvm.sv


simv:
	$(SIMV_DIR) $(SIMV_OPTS)

verdi:
	verdi -dbdir $(BUILD_DIR)/simv.daidir -ssf $(BUILD_DIR)/wave.fsdb &

clean:
	rm -rf $(BUILD_DIR) csrc novas* ucli.key verdiLog files.f *.fsdb inter.fsdb .inter.fsdb.tbsim sys* 

.PHONY: all vcs simv verdi clean








